import os
import sys
import asyncio
from browser_use import Agent, Browser, BrowserConfig
from langchain_anthropic import ChatAnthropic

# 👁️ NEXUS VISION MODULE (v2026.1)
# Этот модуль дает ИИ-агентам возможность ПРОСМАТРИВАТЬ локальные HTML файлы
# или сайты в реальном браузере Chromium для проведения дизайн-аудита QA.

async def analyze_ui(target_url: str):
    print(f"[VISION MODULE] Инициализация Chrome для анализа: {target_url}")
    
    # Режим headless=False открывает реальный браузер у вас на экране, 
    # чтобы вы видели, куда смотрит ИИ.
    browser = Browser(
        config=BrowserConfig(headless=False)
    )
    
    # Подключение "мозгов" к "глазам"
    llm = ChatAnthropic(
        model_name="claude-3-5-sonnet-latest",
        api_key=os.getenv("ANTHROPIC_API_KEY", "")
    )
    
    # Строгий промпт-инструкция для QA тестировщика
    task_prompt = f"""
    Navigate to {target_url}.
    This is a UI generated by the NEXUS OS. You must act as an Awwwards-level Art Director.
    1. Look at the webpage layout, typography, and visual hierarchy.
    2. Check for overlapping elements, unreadable text, overlapping animations, or generic 'bootstrap-style' design.
    3. Verify if it aligns with Dieter Rams or Premium Tech aesthetics (minimalism, strong negative space, perfect contrast).
    4. Provide a brutal, 3-point actionable critique of what to fix in CSS/HTML to make it perfectly premium.
    """
    
    agent = Agent(
        task=task_prompt,
        llm=llm,
        browser=browser,
    )
    
    print("[VISION MODULE] Глаза открыты. Начинаю аудит интерфейса...")
    result = await agent.run()
    
    print("\n===============================")
    print("💎 ОТЧЕТ АНАЛИЗА ЗРЕНИЕМ (QA)")
    print("===============================\n")
    # Извлечение финального ответа из объекта истории
    print(result.final_result())
    
    await browser.close()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python vision_agent.py <URL_OR_LOCAL_FILE_PATH>")
        print("Example: python vision_agent.py ../outputs/NEXUS_Presentation_Site.html")
        sys.exit(1)
        
    target = sys.argv[1]
    
    # Автоматическая конвертация локального D:\ пути в формат file:/// для Chrome
    if os.path.exists(target):
        target = f"file:///{os.path.abspath(target).replace(chr(92), '/')}"
        
    asyncio.run(analyze_ui(target))
