#!/usr/bin/env python3
"""
TAILWIND__X__GPG [NEXUS SYNTHESIZED Gen-1]
Mission: Build a security audit and vulnerability detection tool
Heritage: TAILWIND + GPG
Role: presentation | Security: high | Interface: api
"""

import sys
import json
import logging
import argparse
from pathlib import Path
from datetime import datetime

logging.basicConfig(level=logging.INFO, format="[%(asctime)s] %(levelname)s: %(message)s")
logger = logging.getLogger("TAILWIND__X__GPG")


class ReportGenerator:
    """Generates human-readable Markdown reports from analysis data."""

    def generate(self, data: dict, title: str = "NEXUS Report") -> str:
        lines = [
            f"# {title}",
            f"",
            f"**Generated:** {datetime.now().isoformat()}",
            f"**Agent:** TAILWIND__X__GPG",
            f"",
            f"## Summary",
            f"",
        ]

        analysis = data.get("analysis", {})
        for key, val in analysis.items():
            if isinstance(val, dict):
                lines.append(f"### {key}")
                for k, v in val.items():
                    lines.append(f"- **{k}**: {v}")
            else:
                lines.append(f"- **{key}**: {val}")

        findings = data.get("enriched_findings", data.get("findings", []))
        if findings:
            lines.extend(["", "## Top Findings", "",
                          "| # | Risk | Type | Source | Detail |",
                          "|---|---|---|---|---|"])
            for i, f in enumerate(findings[:15], 1):
                lines.append(f"| {i} | {f.get('risk_score', '?')} | {f.get('type', '?')} | {f.get('file', '?')} | {str(f.get('content', ''))[:60]} |")

        lines.extend(["", "---", f"*Auto-generated by NEXUS Pipeline*"])
        return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="TAILWIND__X__GPG")
    parser.add_argument("--input", required=True, help="Analysis JSON")
    parser.add_argument("--output", default="report.md", help="Output Markdown")
    parser.add_argument("--title", default="NEXUS Intelligence Report", help="Report title")
    args = parser.parse_args()

    data = json.loads(Path(args.input).read_text(encoding="utf-8"))
    gen = ReportGenerator()
    md = gen.generate(data, title=args.title)

    Path(args.output).write_text(md, encoding="utf-8")
    logger.info(f"[DONE] Report -> {args.output}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)
    except Exception as e:
        logger.critical(f"FATAL: {e}")
        sys.exit(1)
