"""
NEXUS AGENT 24 — QWEN FARMER v1.0
====================================
Mission: Autonomous enrichment of all 1446 Wiki repositories
         using local Qwen2.5-coder:3b via Ollama API.

For each repo it generates NEXUS_ANALYSIS.md containing:
  - Russian summary (2-3 sentences)
  - Domain tags (OSINT / AI / ROBOTICS / CRYPTO / LEGAL / MATH / UAV / OTHER)
  - NEXUS Value Score (1-10)
  - Key technologies
  - Recommended use in NEXUS factory

Run: python PROJECT/WIKI-AGENT/24_WIKI_QWEN_FARMER.py
"""

import os
import json
import time
import requests
from pathlib import Path
from datetime import datetime

# ─── CONFIG ───────────────────────────────────────────────────────────────────
WIKI_ROOT   = Path(r"e:\Downloads\--ANTIGRAVITY store\IDE-NEXUS\PROJECT\WIKI")
OLLAMA_URL  = "http://localhost:11434/api/generate"
MODEL       = "qwen2.5-coder:3b"
OUTPUT_FILE = "NEXUS_ANALYSIS.md"
STATE_FILE  = WIKI_ROOT / "nexus_farm_state.json"
DELAY_SEC   = 0.8   # pause between requests to avoid GPU overheating

# ─── PROMPT TEMPLATE ──────────────────────────────────────────────────────────
PROMPT_TEMPLATE = """You are NEXUS Intelligence Analyst. You are GOVERNED BY THE NEXUS CONSTITUTION (100 LAWS).
Analyze this GitHub repository and respond ONLY in the exact JSON format below.

### MANDATORY GUIDELINES:
1. **LAW-100 (Zero Hallucination)**: If the README is empty or unclear, set nexus_value to 0 and state "Unknown" in summary.
2. **LAW-60 (Consistency)**: Ensure classifications do not contradict existing NEXUS standards.
3. **LAW-43 (Data Sovereignty)**: If the tool sends data to external APIs, flag it in 'nexus_use'.
4. **LAW-88 (Attribution)**: Focus on extracting the core value for the NEXUS factory.

Repository: {repo_name}
README content (first 1500 chars):
{readme_content}

Respond with ONLY this JSON (no markdown, no explanation):
{{
  "summary_ru": "2-3 предложения описания на русском языке",
  "domain": "ONE OF: OSINT|AI|ROBOTICS|CRYPTO|LEGAL|MATH|UAV|SECURITY|WEB|SYSTEMS|DATA|OTHER",
  "nexus_value": 7,
  "technologies": ["tech1", "tech2", "tech3"],
  "nexus_use": "Как использовать в NEXUS factory (1 предложение на русском)"
}}"""

# ─── HELPERS ──────────────────────────────────────────────────────────────────
def load_state() -> dict:
    if STATE_FILE.exists():
        return json.loads(STATE_FILE.read_text(encoding="utf-8"))
    return {"processed": [], "failed": [], "started": str(datetime.now())}

def save_state(state: dict):
    STATE_FILE.write_text(json.dumps(state, ensure_ascii=False, indent=2), encoding="utf-8")

def get_readme(repo_dir: Path) -> str:
    for name in ["README.md", "README.rst", "README.txt", "README", "readme.md"]:
        p = repo_dir / name
        if p.exists():
            return p.read_text(encoding="utf-8", errors="ignore")[:1500]
    return f"No README found. Repo name: {repo_dir.name}"

def query_ollama(prompt: str) -> dict | None:
    try:
        resp = requests.post(
            OLLAMA_URL,
            json={"model": MODEL, "prompt": prompt, "stream": False},
            timeout=60
        )
        if resp.status_code != 200:
            return None
        raw = resp.json().get("response", "")
        # Extract JSON from response
        start = raw.find("{")
        end   = raw.rfind("}") + 1
        if start == -1 or end == 0:
            return None
        return json.loads(raw[start:end])
    except Exception as e:
        print(f"    [!] Ollama error: {e}")
        return None

def write_analysis(repo_dir: Path, data: dict, repo_name: str):
    content = f"""# NEXUS Analysis: {repo_name}

> **Generated by NEXUS Agent 24 (Qwen2.5-coder:3b) — {datetime.now().strftime('%Y-%m-%d %H:%M')}**

## Summary
{data.get('summary_ru', 'N/A')}

## Classification
| Field | Value |
|-------|-------|
| **Domain** | `{data.get('domain', 'OTHER')}` |
| **NEXUS Value** | {'⭐' * int(data.get('nexus_value', 5))} {data.get('nexus_value', 5)}/10 |

## Key Technologies
{chr(10).join(f'- `{t}`' for t in data.get('technologies', []))}

## NEXUS Application
{data.get('nexus_use', 'N/A')}
"""
    (repo_dir / OUTPUT_FILE).write_text(content, encoding="utf-8")

# ─── MAIN LOOP ────────────────────────────────────────────────────────────────
def main():
    print("\n" + "=" * 62)
    print("  NEXUS AGENT 24  QWEN FARMER v1.0")
    print(f"  Model: {MODEL} | Wiki repos: scanning...")
    print("=" * 62 + "\n")

    # Check Ollama is alive
    try:
        requests.get("http://localhost:11434", timeout=3)
    except Exception:
        print("[FATAL] Ollama is not running! Start it with: ollama serve")
        return

    state = load_state()
    processed_set = set(state["processed"])

    # Collect all repo dirs
    repos = sorted([d for d in WIKI_ROOT.iterdir() if d.is_dir() and not d.name.startswith("__")])
    total = len(repos)
    
    print(f"[*] Total repos: {total}")
    print(f"[*] Already processed: {len(processed_set)}")
    print(f"[*] Remaining: {total - len(processed_set)}\n")

    for i, repo_dir in enumerate(repos, 1):
        repo_name = repo_dir.name

        # Skip already processed
        if repo_name in processed_set:
            continue

        # Skip if analysis already exists and is fresh
        analysis_file = repo_dir / OUTPUT_FILE
        if analysis_file.exists():
            processed_set.add(repo_name)
            state["processed"].append(repo_name)
            continue

        print(f"  [{i}/{total}] Processing: {repo_name[:55]:<55}", end=" ", flush=True)

        readme = get_readme(repo_dir)
        prompt = PROMPT_TEMPLATE.format(repo_name=repo_name, readme_content=readme)

        result = query_ollama(prompt)

        if result:
            write_analysis(repo_dir, result, repo_name)
            processed_set.add(repo_name)
            state["processed"].append(repo_name)
            score = result.get('nexus_value', '?')
            domain = result.get('domain', '?')
            print(f"✓ [{domain}] score={score}")
        else:
            state["failed"].append(repo_name)
            print("✗ FAILED")

        # Save state every 10 repos
        if i % 10 == 0:
            save_state(state)

        time.sleep(DELAY_SEC)

    save_state(state)
    processed = len(state['processed'])
    failed = len(state['failed'])
    print(f"\n{'='*62}")
    print(f"  [DONE] Processed: {processed} | Failed: {failed}")
    print(f"  State saved: {STATE_FILE}")
    print(f"{'='*62}\n")

if __name__ == "__main__":
    main()
