#!/usr/bin/env python3
"""
HYBRID_ALLUXIO_x_AUTOAWQ v2.0 [NEXUS OSINT ORCHESTRATOR]
==========================================================
Heritage: Alluxio (Data Orchestration) + AutoAWQ (Efficient Inference)
Role:     ORCHESTRATOR - Launches Collector -> Analyzer pipeline, generates final report
Input:    Target directory (--target)
Output:   Final consolidated intelligence report (Markdown + JSON)

DNA Signature: Network=0.6, Intelligence=0.7, Autonomy=0.3, Hardware=0.2, Stealth=0.0, Scale=0.5
Security:      none
Interface:     CLI
Latency:       batch
"""

import sys
import json
import time
import logging
import argparse
import subprocess
from pathlib import Path
from datetime import datetime

logging.basicConfig(level=logging.INFO, format="[%(asctime)s] %(levelname)s: %(message)s")
logger = logging.getLogger("NEXUS-ORCHESTRATOR")

# ── Constants ────────────────────────────────────────────────────────────
AGENT_DIR = Path(__file__).resolve().parent
COLLECTOR = AGENT_DIR / "HYBRID_TROUBLESHOOTING_x_CRATE_synthesized_agent.py"
ANALYZER  = AGENT_DIR / "HYBRID_AUTOGLUON_x_ALLUXIO_synthesized_agent.py"
# ────────────────────────────────────────────────────────────────────────


def run_agent(script: Path, args: list, label: str) -> bool:
    """Execute a child agent as subprocess. Returns True on success."""
    if not script.exists():
        logger.error(f"[{label}] Agent not found: {script}")
        return False

    cmd = [sys.executable, str(script)] + args
    logger.info(f"[{label}] Launching: {script.name} {' '.join(args)}")

    t0 = time.monotonic()
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        elapsed = time.monotonic() - t0
        
        if result.returncode == 0:
            logger.info(f"[{label}] Completed in {elapsed:.1f}s (exit 0)")
            if result.stdout.strip():
                print(result.stdout)
            return True
        else:
            logger.error(f"[{label}] Failed (exit {result.returncode}, {elapsed:.1f}s)")
            if result.stderr:
                for line in result.stderr.strip().split("\n")[-5:]:
                    logger.error(f"  {line}")
            return False

    except subprocess.TimeoutExpired:
        logger.error(f"[{label}] Timeout after 120s")
        return False
    except Exception as e:
        logger.error(f"[{label}] Error: {e}")
        return False


def generate_markdown_report(analysis_path: Path, output_md: Path):
    """Generate a human-readable Markdown summary from the analysis JSON."""
    if not analysis_path.exists():
        logger.warning("[REPORT] Analysis JSON not found, skipping Markdown generation.")
        return

    data = json.loads(analysis_path.read_text(encoding="utf-8"))
    a    = data["analysis"]
    findings = data.get("enriched_findings", [])

    lines = [
        f"# NEXUS OSINT Report",
        f"",
        f"**Generated:** {datetime.now().isoformat()}",
        f"**Pipeline:** Collector v2.0 -> Analyzer v2.0 -> Orchestrator v2.0",
        f"",
        f"## Summary",
        f"",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Total findings | {a['total_findings']} |",
        f"| Top risk score | {a['top_risk_score']} |",
        f"| Mean risk score | {a['mean_risk_score']} |",
        f"| Risk verdict | **{a['risk_verdict']}** |",
        f"",
        f"### Priority Breakdown",
        f"",
    ]

    for p in ["P0-IMMEDIATE", "P1-URGENT", "P2-REVIEW", "P3-INFO"]:
        cnt = a["by_priority"].get(p, 0)
        if cnt:
            lines.append(f"- **{p}**: {cnt}")

    lines.append("")
    lines.append("## Top 10 Findings")
    lines.append("")
    lines.append("| # | Risk | Rule | File | Line | Remediation |")
    lines.append("|---|---|---|---|---|---|")

    for i, f in enumerate(findings[:10], 1):
        lines.append(
            f"| {i} | {f['risk_score']:.2f} | `{f['rule_id']}` | "
            f"`{f['file']}` | {f['line']} | {f['remediation'][:60]} |"
        )

    if len(findings) > 10:
        lines.append(f"")
        lines.append(f"*...and {len(findings) - 10} more findings in the full JSON report.*")

    lines.append("")
    lines.append("---")
    lines.append(f"*Report generated by NEXUS OSINT Pipeline (3 agents, fully autonomous)*")

    output_md.write_text("\n".join(lines), encoding="utf-8")
    logger.info(f"[REPORT] Markdown -> {output_md}")


def orchestrate(target: Path, work_dir: Path):
    """Execute the full OSINT pipeline: Collector -> Analyzer -> Report."""
    work_dir.mkdir(parents=True, exist_ok=True)

    collector_output = work_dir / "1_collector_report.json"
    analyzer_output  = work_dir / "2_analysis_report.json"
    final_md         = work_dir / "OSINT_REPORT.md"

    t_total = time.monotonic()

    print(f"\n{'='*60}")
    print(f"  NEXUS OSINT ORCHESTRATOR v2.0")
    print(f"  Target: {target}")
    print(f"  Work:   {work_dir}")
    print(f"{'='*60}\n")

    # ── Stage 1: COLLECT ─────────────────────────────────────────────────
    ok1 = run_agent(COLLECTOR, ["--target", str(target), "--output", str(collector_output)], "COLLECT")
    if not ok1:
        logger.error("[ABORT] Collection stage failed.")
        sys.exit(1)

    # ── Stage 2: ANALYZE ─────────────────────────────────────────────────
    ok2 = run_agent(ANALYZER, ["--input", str(collector_output), "--output", str(analyzer_output)], "ANALYZE")
    if not ok2:
        logger.error("[ABORT] Analysis stage failed.")
        sys.exit(1)

    # ── Stage 3: REPORT ──────────────────────────────────────────────────
    generate_markdown_report(analyzer_output, final_md)

    elapsed = time.monotonic() - t_total
    print(f"\n{'='*60}")
    print(f"  PIPELINE COMPLETE ({elapsed:.1f}s)")
    print(f"  [1] Collector: {collector_output.name}")
    print(f"  [2] Analysis:  {analyzer_output.name}")
    print(f"  [3] Report:    {final_md.name}")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="NEXUS OSINT Orchestrator v2.0 -- Full pipeline"
    )
    parser.add_argument("--target", default=".", help="Directory to scan")
    parser.add_argument("--workdir", default="osint_output", help="Output directory for reports")
    args = parser.parse_args()

    try:
        orchestrate(Path(args.target).resolve(), Path(args.workdir).resolve())
    except KeyboardInterrupt:
        sys.exit(0)
    except Exception as e:
        logger.critical(f"FATAL: {e}")
        sys.exit(1)
